---
kind: Service
apiVersion: v1
metadata:
  name: todo-api
  labels:
    name: todo-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http-server
      protocol: TCP
  selector:
    name: todo-api
